### ISSUE TITLE
Related use-case?

### ISSUE THREAD

**Issue by andybak** [saulshanabrook/django-externaltestserver#1]
I'd like to write some integration tests that rely on testing against a snapshot of the production db.

The idea is to ferret out problems that might be unanticipated - the kind of stuff that comes out of the interaction between our code and client data.

I struggled to find a good way to populate the database. as the test db is torn down each time it adds a big overhead to running tests. The data I want to test against is already present in my local development db. Even ignoring this, the problem then becomes one of loading SQL during the test setup as dumping/loading fixtures introduces its own problems.

I think the only difference in my use-case is that I might not want to use Selenium tests. i.e. I want my test code to use the test client - or pure python calls.

So my question is probably: - "is there enough overlap for me to consider your code as a starting point"?

(It's also possible that my use-case is fairly trivial to solve - I only spent a brief amount of time on it before moving on to more urgent tasks)

**Comment by saulshanabrook** [comment]
To clarify, do you just wanna run some tests against your main database, instead of the testing database?

Do you want it to just run some tests on the database and not clean anything up after?

**Comment by andybak** [comment]
More like the former I should think.

**Comment by saulshanabrook** [comment]
Well if you set `DATABASES['default']['TEST'] = {'NAME': DATABASES['default']['NAME']}` in your `settings.py` and use `--keepdb` when running tests then it will execute against your normal database. Is that what you mean?

**Comment by andybak** [comment]
> It's also possible that my use-case is fairly trivial to solve 

Seems that was the case! I had spent time messing around subclassing on LiveServerTestCase - that sounds much simpler.

I'll give it a try.
